name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
            👋 感谢您提交 Issue！请尝试在一个纯新的项目文件中复现你的问题
            📌 请确认已提供：问题描述、复现步骤、项目文件、环境信息（版本/系统）
            🕒 作者会尽快跟进
        pr-message: |
            ✨ 感谢您的PR贡献！
            📝 请确认PR符合项目提交规范，我们会尽快审核~
